blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/ironsheep/lovelace-rpi-monitor-card
    about: Supporting Documentation is all at the repository README
